param([string]$PrivateRoot=(Join-Path (Split-Path $PSScriptRoot -Parent) '.local/private-import'))
$ErrorActionPreference='Stop'
[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$privatePath=[IO.Path]::GetFullPath($PrivateRoot)
$dummyBase=Join-Path $privatePath 'dummy'
$dummyRoot=Join-Path $dummyBase ('run-'+[datetime]::UtcNow.ToString('yyyyMMddTHHmmssfff'))
$manifest=Get-Content -LiteralPath (Join-Path $privatePath 'source-manifest.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$app=$null; $sources=@(); $audit=@{originalRowsRead=$false;activeSourceOpened=$false;thirdPartyConnectionsFollowed=$false;tablesCreated=0;syntheticRowsCreated=0;linksRedirected=0;relationsCreated=0;definitionObjectsCreated=0;limitations=@();sourceHashesUnchanged=$false;dummyLinksVerified=$false;relationIntegrityVerified=$false}
function Release($object) { if ($object) { [void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($object) } }
function Add-AuditIssue([string]$code) { $script:audit.limitations+=@{code=$code} }
function Fill-Synthetic($target) {
  foreach ($table in $target.TableDefs) {
    if ($table.Name -match '^(MSys|~)' -or [string]$table.Connect) { continue }
    try {
      # All rows originate here, never from a source Recordset. Constant values align PK/FK values.
      $suppressed=$false
      try { if ([string]$table.ValidationRule) { $suppressed=$true }; $table.ValidationRule='' } catch {}
      foreach ($field in $table.Fields) {
        try { if ([string]$field.DefaultValue) { $suppressed=$true }; $field.DefaultValue='' } catch {}
        try { if ([string]$field.ValidationRule) { $suppressed=$true }; $field.ValidationRule='' } catch {}
      }
      if ($suppressed) { Add-AuditIssue 'DUMMY_DEFAULTS_VALIDATION_SUPPRESSED' }
      $columnNames=@(); $columnValues=@()
      foreach ($field in $table.Fields) {
        if (($field.Attributes -band 16) -ne 0) { continue } # AutoNumber is generated by the new DB.
        $value=$null
        switch ([int]$field.Type) {
          1 { $value='False' }
          {$_ -in 2,3,4,5,6,7,16,19,20,21} { $value='1' }
          8 { $value='#2000-01-01#' }
          {$_ -in 10,12,18} { $value="'X'" }
          15 { $value="'{00000000-0000-0000-0000-000000000001}'" }
          default { if ($field.Required) { throw 'Unsupported required synthetic field.' } }
        }
        if ($null -ne $value) { $columnNames+=('['+([string]$field.Name).Replace(']',']]')+']'); $columnValues+=$value }
      }
      $tableName='['+([string]$table.Name).Replace(']',']]')+']'
      $target.Execute(('INSERT INTO '+$tableName+' ('+($columnNames -join ',')+') VALUES ('+($columnValues -join ',')+')'),128)
      $script:audit.syntheticRowsCreated++
    } catch { Add-AuditIssue 'SYNTHETIC_ROW_UNAVAILABLE' }
  }
}
function Copy-LocalSchema($source,[string]$sourcePath) {
  foreach ($table in $source.TableDefs) {
    if ($table.Name -match '^(MSys|~)' -or [string]$table.Connect) { continue }
    try {
      $app.DoCmd.TransferDatabase(0,'Microsoft Access',$sourcePath,0,[string]$table.Name,[string]$table.Name,$true,$false)
      $destination=$app.CurrentDb(); $copied=$destination.TableDefs.Item([string]$table.Name)
      foreach ($field in $table.Fields) { $copied.Fields.Item([string]$field.Name).Required=[bool]$field.Required }
      $destination.Close(); Release $destination
      $script:audit.tablesCreated++
    }
    catch { Add-AuditIssue 'TABLE_SCHEMA_UNAVAILABLE' }
  }
}
function Copy-Relations($source,$target) {
  foreach ($relation in $source.Relations) {
    if ($relation.Table -match '^(MSys|~)' -or $relation.ForeignTable -match '^(MSys|~)') { continue }
    try {
      $exists=$false; foreach ($existing in $target.Relations) { if ($existing.Name -eq $relation.Name) { $exists=$true; break } }
      if ($exists) { continue }
      $new=$target.CreateRelation([string]$relation.Name,[string]$relation.Table,[string]$relation.ForeignTable,[int]$relation.Attributes)
      foreach ($field in $relation.Fields) { $newField=$new.CreateField([string]$field.Name); $newField.ForeignName=[string]$field.ForeignName; $new.Fields.Append($newField) }
      $target.Relations.Append($new); $script:audit.relationsCreated++
    } catch { Add-AuditIssue 'RELATION_UNAVAILABLE' }
  }
}
try {
  $audit.stage='preservation'
  if (Test-Path -LiteralPath (Join-Path $dummyRoot 'backend.accdb')) { throw 'Dummy target already exists; preserve it.' }
  New-Item -ItemType Directory -Path $dummyRoot -Force | Out-Null
  $hashes=@(); foreach ($entry in $manifest) {
    foreach ($path in @($entry.originalPath,$entry.copyPath)) {
      $hash=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash
      if ($path -eq $entry.originalPath -and $hash -ne $entry.originalHash) { throw 'Original preservation hash mismatch.' }
      $hashes+=@{path=$path;hash=$hash}
    }
  }
  $audit.preservationCopiesMatchOriginalManifest=$true
  foreach ($entry in $manifest) { if ((Get-FileHash -LiteralPath ([string]$entry.copyPath)).Hash -ne $entry.originalHash) { $audit.preservationCopiesMatchOriginalManifest=$false } }
  $audit.stage='com'
  $app=New-Object -ComObject Access.Application; $app.Visible=$false; $app.AutomationSecurity=3
  $backEntry=$manifest | Where-Object {$_.role -match '^backend(?:\.|$)'}
  $frontEntry=$manifest | Where-Object {$_.role -match '^frontend(?:\.|$)'}
  if (-not $backEntry -or -not $frontEntry) { throw 'Required schema sources missing.' }
  $workingBack=Join-Path $dummyRoot 'readonly-source-backend.accdb'; $workingFront=Join-Path $dummyRoot 'readonly-source-frontend.mdb'
  Copy-Item -LiteralPath ([string]$backEntry.originalPath) -Destination $workingBack
  Copy-Item -LiteralPath ([string]$frontEntry.originalPath) -Destination $workingFront
  (Get-Item -LiteralPath $workingBack).IsReadOnly=$true; (Get-Item -LiteralPath $workingFront).IsReadOnly=$true
  $workingHashes=@(@{path=$workingBack;hash=(Get-FileHash -LiteralPath $workingBack).Hash},@{path=$workingFront;hash=(Get-FileHash -LiteralPath $workingFront).Hash})
  $audit.stage='readonly-schema'
  $backSource=$app.DBEngine.OpenDatabase($workingBack,$false,$true); $sources+=$backSource
  $frontSource=$app.DBEngine.OpenDatabase($workingFront,$false,$true); $sources+=$frontSource
  $backPath=Join-Path $dummyRoot 'backend.accdb'; $frontPath=Join-Path $dummyRoot 'frontend.accdb'
  $audit.stage='new-backend'
  $app.NewCurrentDatabase($backPath,12)
  Copy-LocalSchema $backSource $workingBack
  $backTarget=$app.CurrentDb(); Fill-Synthetic $backTarget; Copy-Relations $backSource $backTarget
  $allowedNames=@(); foreach ($table in $backTarget.TableDefs) { if ($table.Name -notmatch '^(MSys|~)' -and -not [string]$table.Connect) { $allowedNames += [string]$table.Name } }
  $backTarget.Close(); Release $backTarget; $app.CloseCurrentDatabase()
  $audit.stage='new-frontend'
  $app.NewCurrentDatabase($frontPath,12)
  Copy-LocalSchema $frontSource $workingFront
  $frontTarget=$app.CurrentDb(); Fill-Synthetic $frontTarget
  foreach ($table in $frontSource.TableDefs) {
    if ($table.Name -match '^(MSys|~)' -or -not [string]$table.Connect) { continue }
    # Merely inspect the link string. Do not resolve or open its original target.
    $connect=[string]$table.Connect
    $known=$false
    if ($connect -match '(?i)(?:^|;)DATABASE=([^;]+)') {
      $referenced=$Matches[1]
      $known=([IO.Path]::GetFileName($referenced) -eq [IO.Path]::GetFileName([string]$backEntry.originalPath))
    }
    if (-not $known -or [string]$table.SourceTableName -notin $allowedNames) { Add-AuditIssue 'THIRD_PARTY_LINK_NOT_CREATED'; continue }
    try {
      $link=$frontTarget.CreateTableDef([string]$table.Name); $link.Connect=";DATABASE=$backPath"; $link.SourceTableName=[string]$table.SourceTableName; $frontTarget.TableDefs.Append($link); $audit.linksRedirected++
    } catch { Add-AuditIssue 'DUMMY_LINK_UNAVAILABLE' }
  }
  foreach ($query in $frontSource.QueryDefs) {
    if ($query.Name -match '^~') { continue }
    if ([string]$query.Connect) { Add-AuditIssue 'EXTERNAL_QUERY_NOT_CREATED'; continue }
    try { [void]$frontTarget.CreateQueryDef([string]$query.Name,[string]$query.SQL); $audit.definitionObjectsCreated++ } catch { Add-AuditIssue 'QUERY_DEFINITION_UNAVAILABLE' }
  }
  Copy-Relations $frontSource $frontTarget
  foreach ($group in @(@{container='Forms';type=2},@{container='Reports';type=3},@{container='Scripts';type=4},@{container='Modules';type=5})) {
    try {
      foreach ($document in $frontSource.Containers.Item($group.container).Documents) {
        try { $app.DoCmd.TransferDatabase(0,'Microsoft Access',$workingFront,$group.type,[string]$document.Name,[string]$document.Name,$true,$false); $audit.definitionObjectsCreated++ }
        catch { Add-AuditIssue 'OBJECT_DEFINITION_UNAVAILABLE' }
      }
    } catch {}
  }
  $audit.dummyLinksVerified=$true
  foreach ($table in $frontTarget.TableDefs) {
    if ([string]$table.Connect -and [string]$table.Connect -ne ";DATABASE=$backPath") { $audit.dummyLinksVerified=$false; throw 'Unexpected dummy link.' }
  }
  $frontTarget.Close(); Release $frontTarget; $app.CloseCurrentDatabase()
  # DAO metadata checks only; relation creation itself enforces PK/FK against newly generated rows.
  $audit.relationIntegrityVerified=(@($audit.limitations | Where-Object {$_.code -in @('RELATION_UNAVAILABLE','SYNTHETIC_ROW_UNAVAILABLE')}).Count -eq 0)
  foreach ($source in $sources) { $source.Close(); Release $source }; $sources=@()
  foreach ($item in ($hashes+$workingHashes)) { if ((Get-FileHash -LiteralPath $item.path -Algorithm SHA256).Hash -ne $item.hash) { throw 'Source changed.' } }
  $audit.sourceHashesUnchanged=$true
  $audit.stage='complete'
  $audit | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath (Join-Path $dummyRoot 'creation-audit.json') -Encoding UTF8
  @{run=Split-Path $dummyRoot -Leaf} | ConvertTo-Json -Compress | Set-Content -LiteralPath (Join-Path $dummyBase 'latest.json') -Encoding UTF8
  @{status='DUMMY_CREATED';tables=$audit.tablesCreated;syntheticRows=$audit.syntheticRowsCreated;links=$audit.linksRedirected;relations=$audit.relationsCreated;definitions=$audit.definitionObjectsCreated;limitations=$audit.limitations.Count;sourceHashesUnchanged=$audit.sourceHashesUnchanged;dummyLinksVerified=$audit.dummyLinksVerified;relationIntegrityVerified=$audit.relationIntegrityVerified} | ConvertTo-Json -Compress
} catch {
  $audit.failureType=$_.Exception.GetType().Name
  $audit.failureCode=$_.Exception.HResult
  Add-AuditIssue 'DUMMY_CREATION_INCOMPLETE'
  if (Test-Path -LiteralPath $dummyRoot) { $audit | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath (Join-Path $dummyRoot 'creation-audit.json') -Encoding UTF8 }
  Write-Output '{"status":"DUMMY_CREATION_INCOMPLETE"}'; exit 1
} finally {
  foreach ($source in $sources) { try { $source.Close() } catch {}; Release $source }
  if ($app) { try { $app.CloseCurrentDatabase() } catch {}; try { $app.Quit(2) } catch {}; Release $app }
  [GC]::Collect(); [GC]::WaitForPendingFinalizers()
}
